export const COUNTRIES = [
  "Afeganistão",
  "África do Sul",
  "Albânia",
  "Alemanha",
  "Andorra",
  "Angola",
  "Anguila",
  "Antártida",
  "Antígua e Barbuda",
  "Arábia Saudita",
  "Argélia",
  "Argentina",
  "Arménia",
  "Aruba",
  "Austrália",
  "Áustria",
  "Azerbaijão",
  "Bahamas",
  "Bahrein",
  "Bangladesh",
  "Barbados",
  "Bélgica",
  "Belize",
  "Benim",
  "Bermudas",
  "Bielorrússia",
  "Bolívia",
  "Bósnia-Herzegovina",
  "Botsuana",
  "Brasil",
  "Brunei",
  "Bulgária",
  "Burkina Faso",
  "Burundi",
  "Butão",
  "Cabo Verde",
  "Camarões",
  "Camboja",
  "Canadá",
  "Cazaquistão",
  "Chade",
  "Chéquia",
  "Chile",
  "China",
  "Chipre",
  "Colômbia",
  "Comores",
  "Coreia do Norte",
  "Coreia do Sul",
  "Costa do Marfim",
  "Costa Rica",
  "Croácia",
  "Cuba",
  "Curaçao",
  "Dinamarca",
  "Djibouti",
  "Dominica",
  "Egito",
  "El Salvador",
  "Emirados Árabes Unidos",
  "Equador",
  "Eritreia",
  "Eslováquia",
  "Eslovénia",
  "Espanha",
  "Essuatíni",
  "Estados Unidos",
  "Estónia",
  "Etiópia",
  "Fiji",
  "Filipinas",
  "Finlândia",
  "França",
  "Gabão",
  "Gâmbia",
  "Gana",
  "Geórgia do Sul e Ilhas Sandwich do Sul",
  "Geórgia",
  "Gibraltar",
  "Granada",
  "Grécia",
  "Gronelândia",
  "Guadalupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guiana Francesa",
  "Guiana",
  "Guiné Equatorial",
  "Guiné-Bissau",
  "Guiné",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungria",
  "Iémen",
  "Ilha Bouvet",
  "Ilha de Man",
  "Ilha de Natal",
  "Ilha Heard e Ilhas McDonald",
  "Ilha Norfolk",
  "Ilhas Åland",
  "Ilhas Caimão",
  "Ilhas Cocos (Keeling)",
  "Ilhas Cook",
  "Ilhas Distantes dos EUA",
  "Ilhas Faroé",
  "Ilhas Malvinas",
  "Ilhas Marianas do Norte",
  "Ilhas Marshall",
  "Ilhas Pitcairn",
  "Ilhas Salomão",
  "Ilhas Turcas e Caicos",
  "Ilhas Virgens Americanas",
  "Ilhas Virgens Britânicas",
  "Índia",
  "Indonésia",
  "Irão",
  "Iraque",
  "Irlanda",
  "Islândia",
  "Israel",
  "Itália",
  "Jamaica",
  "Japão",
  "Jersey",
  "Jordânia",
  "Kosovo",
  "Koweit",
  "Laos",
  "Lesoto",
  "Letónia",
  "Líbano",
  "Libéria",
  "Líbia",
  "Liechtenstein",
  "Lituânia",
  "Luxemburgo",
  "Macau",
  "Macedónia do Norte",
  "Madagáscar",
  "Malásia",
  "Maláui",
  "Maldivas",
  "Mali",
  "Malta",
  "Marrocos",
  "Martinica",
  "Maurícia",
  "Mauritânia",
  "Mayotte",
  "México",
  "Mianmar (Birmânia)",
  "Micronésia",
  "Moçambique",
  "Moldávia",
  "Mónaco",
  "Mongólia",
  "Monserrate",
  "Montenegro",
  "Namíbia",
  "Nauru",
  "Nepal",
  "Nicarágua",
  "Níger",
  "Nigéria",
  "Niue",
  "Noruega",
  "Nova Caledónia",
  "Nova Zelândia",
  "Omã",
  "Países Baixos Caribenhos",
  "Países Baixos",
  "Palau",
  "Panamá",
  "Papua-Nova Guiné",
  "Paquistão",
  "Paraguai",
  "Peru",
  "Polinésia Francesa",
  "Polónia",
  "Porto Rico",
  "Portugal",
  "Qatar",
  "Quénia",
  "Quirguistão",
  "Quiribati",
  "Reino Unido",
  "República Centro-Africana",
  "República Democrática do Congo",
  "República Dominicana",
  "República Popular do Congo",
  "Reunião",
  "Roménia",
  "Ruanda",
  "Rússia",
  "Saara Ocidental",
  "Saint Pierre e Miquelon",
  "Samoa Americana",
  "Samoa",
  "San Marino",
  "Santa Helena",
  "Santa Lúcia",
  "Santa Sé",
  "São Bartolomeu",
  "São Cristóvão e Neves",
  "São Martinho",
  "São Tomé e Príncipe",
  "São Vicente e Granadinas",
  "Senegal",
  "Serra Leoa",
  "Sérvia",
  "Seychelles",
  "Singapura",
  "Síria",
  "Somália",
  "Sri Lanka",
  "Sudão do Sul",
  "Sudão",
  "Suécia",
  "Suíça",
  "Suriname",
  "Svalbard e Jan Mayen",
  "Tailândia",
  "Taiwan",
  "Tajiquistão",
  "Tanzânia",
  "Terras Austrais e Antárticas Francesas",
  "Território Britânico do Oceano Índico",
  "Territórios palestinos",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trindade e Tobago",
  "Tunísia",
  "Turquemenistão",
  "Turquia",
  "Tuvalu",
  "Ucrânia",
  "Uganda",
  "Uruguai",
  "Uzbequistão",
  "Vanuatu",
  "Venezuela",
  "Vietname",
  "Wallis e Futuna",
  "Zâmbia",
  "Zimbábue",
];
